# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/EBAZ4205/P15_VGA_TEST/VGA_TEST.cache/wt [current_project]
set_property parent.project_path E:/EBAZ4205/P15_VGA_TEST/VGA_TEST.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/EBAZ4205/P15_VGA_TEST/VGA_TEST.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/EBAZ4205/P15_VGA_TEST/VGA_TEST.srcs/sources_1/new/VGA_CTRL.v
  E:/EBAZ4205/P15_VGA_TEST/VGA_TEST.srcs/sources_1/new/VGA_DATA.v
  E:/EBAZ4205/P15_VGA_TEST/VGA_TEST.srcs/sources_1/new/VGA_TEST.v
}
add_files E:/EBAZ4205/P15_VGA_TEST/VGA_TEST.srcs/sources_1/bd/zynq/zynq.bd
set_property used_in_implementation false [get_files -all e:/EBAZ4205/P15_VGA_TEST/VGA_TEST.srcs/sources_1/bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all E:/EBAZ4205/P15_VGA_TEST/VGA_TEST.srcs/sources_1/bd/zynq/zynq_ooc.xdc]

read_ip -quiet E:/EBAZ4205/P15_VGA_TEST/VGA_TEST.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/EBAZ4205/P15_VGA_TEST/VGA_TEST.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/EBAZ4205/P15_VGA_TEST/VGA_TEST.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/EBAZ4205/P15_VGA_TEST/VGA_TEST.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/EBAZ4205/P15_VGA_TEST/VGA_TEST.srcs/constrs_1/new/VGA_TEST.xdc
set_property used_in_implementation false [get_files E:/EBAZ4205/P15_VGA_TEST/VGA_TEST.srcs/constrs_1/new/VGA_TEST.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top VGA_TEST -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef VGA_TEST.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file VGA_TEST_utilization_synth.rpt -pb VGA_TEST_utilization_synth.pb"
